apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bxbs5pyii-go
  janus-idp.io/tekton: bxbs5pyii-go
  backstage.io/kubernetes-id: bxbs5pyii-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bxbs5pyii-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
