apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bxbs5pyii-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bxbs5pyii-go 
  name: bxbs5pyii-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bxbs5pyii-go 
